---

name: Fetch RPM package and dependencies for Rhel8/Centos8 target
on:
  workflow_dispatch:
    inputs:
      targetHost:
        description: 'Target host'
        default: 'redhat/ubi8:8.4'
        required: true
      packageName:
        description: 'Package to fetch'
        required: true

jobs:
  FetchingOnTarget:
    runs-on: ubuntu-latest
    container:
      image: ${{ github.event.inputs.targetHost }}
    steps:
    - name: Install repositories
      run: |
        mkdir "export"
        sed -ie "s/enabled=.*/enabled=0/" /etc/yum/pluginconf.d/subscription-manager.conf || true
        yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
        yum -y install https://dl.fedoraproject.org/pub/epel/epel-next-release-latest-8.noarch.rpm
        yum -y install yum-utils
        yum-config-manager --add-repo http://mirror.centos.org/centos/8-stream/BaseOS/x86_64/os/
        yum-config-manager --add-repo http://mirror.centos.org/centos/8-stream/AppStream/x86_64/os/
        yum-config-manager --add-repo http://mirror.centos.org/centos/8-stream/PowerTools/x86_64/os/
        yum-config-manager --add-repo http://mirror.centos.org/centos/8-stream/extras/x86_64/os/
        yum-config-manager --add-repo http://mirror.centos.org/centos/8-stream/HighAvailability/x86_64/os/
        yum-config-manager --add-repo http://mirror.centos.org/centos/8-stream/RT/x86_64/os/
        yum-config-manager --add-repo http://mirror.centos.org/centos/8-stream/ResilientStorage/x86_64/os/
        yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
        yum-config-manager --add-repo https://nginx.org/packages/centos/8/x86_64/
        yum-config-manager --add-repo https://download.postgresql.org/pub/repos/yum/12/redhat/rhel-8-x86_64/
        yum-config-manager --add-repo https://download.postgresql.org/pub/repos/yum/13/redhat/rhel-8-x86_64/
        yum-config-manager --add-repo https://download.postgresql.org/pub/repos/yum/14/redhat/rhel-8-x86_64/
        yum-config-manager --add-repo https://download.postgresql.org/pub/repos/yum/common/redhat/rhel-8-x86_64/
        yum-config-manager --add-repo https://download.virtualbox.org/virtualbox/rpm/el/8/x86_64/
        yum-config-manager --add-repo https://releases.ansible.com/ansible-tower/cli/ansible-tower-cli-el8.repo
        yum clean all
        yum makecache
        
    - name: Check Match in repositories and test dry installation
      run : |
        repoquery *${{ github.event.inputs.packageName }}*
        dnf info "${{ github.event.inputs.packageName }}"
        yes no | dnf install "${{ github.event.inputs.packageName }}" || true
        
    - name: Fetch package and dependencies
      run: |
        dnf download --resolve --downloaddir="export/" ${{ github.event.inputs.packageName }}
        
    - name: Upload Archive
      uses: actions/upload-artifact@v3.1.0
      with:
        name: export
        path: export
        retention-days: 2
